import { directSigningScenario, intentScenario } from '../types'

export const accountScenarios = [
  intentScenario({
    id: 'accounts/safe-1.4.1-adapter-1-defaults-new',
    primaryCategory: 'accounts',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'safe-ecdsa',
    caseId: 'same-chain-noop',
    axes: {
      account: [
        'safe',
        'safe:1.4.1',
        'safe-adapter:1.0.0',
        'version:default',
        'state:new',
        'factory:default',
        'salt:default',
        'nonce:default',
      ],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain', 'calls:single'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: ['smoke', 'golden-vector'],
    support: { level: 'live' },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'accounts/safe-1.4.1-adapter-2-explicit-deployed',
    primaryCategory: 'accounts',
    workflow: 'intent',
    mode: 'execute',
    fixtureId: 'safe-ecdsa',
    caseId: 'same-chain-noop',
    axes: {
      account: [
        'safe',
        'safe:1.4.1',
        'safe-adapter:2.0.0',
        'version:explicit',
        'state:deployed',
        'salt:explicit',
        'nonce:explicit',
      ],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain', 'calls:single', 'sponsorship:sponsored'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: ['stateful'],
    support: { level: 'live' },
    expected: { kind: 'success' },
    setup: {
      identity: 'ephemeral',
      preconditions: ['account-deployed'],
      funding: 'none',
      uniqueness: 'funding-lane',
      cleanup: 'none',
    },
    comparison: 'isolated-state',
    terminalAssertions: ['intent-completed', 'no-failed-operations'],
    timeoutMs: 180_000,
  }),
  intentScenario({
    id: 'accounts/undeployed-safe-passkey-cross-chain',
    primaryCategory: 'accounts',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'safe-passkey',
    caseId: 'cross-chain-noop',
    axes: {
      account: ['safe', 'safe:1.4.1', 'state:new'],
      owner: ['passkey:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:cross-chain', 'calls:single'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: ['high-risk:undeployed-safe-passkey-cross-chain', 'live-gap'],
    support: {
      level: 'dry-run-only',
      limitation:
        'Live passkey execution is not provisioned in the testnet lane.',
    },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'accounts/nexus-1.0.2-new',
    primaryCategory: 'accounts',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'nexus-ecdsa',
    caseId: 'same-chain-noop',
    axes: {
      account: ['nexus', 'nexus:1.0.2', 'version:explicit', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain', 'calls:single'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: ['golden-vector'],
    support: { level: 'live' },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'accounts/nexus-1.2.0-adopted',
    primaryCategory: 'accounts',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'nexus-ecdsa',
    caseId: 'same-chain-noop',
    axes: {
      account: ['nexus', 'nexus:1.2.0', 'version:explicit', 'state:adopted'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain', 'flow:prepare-sign-submit'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: ['negative'],
    support: { level: 'live' },
    expected: {
      kind: 'failure',
      stage: 'submit',
      errorClass: 'SimulationFailedError',
      code: 'SIMULATION_FAILED',
      messageInvariant: 'InvalidSignature',
    },
  }),
  intentScenario({
    id: 'accounts/nexus-rhinestone-beta-execute',
    primaryCategory: 'accounts',
    workflow: 'intent',
    mode: 'execute',
    fixtureId: 'nexus-ecdsa',
    caseId: 'same-chain-noop',
    axes: {
      account: [
        'nexus',
        'nexus:rhinestone-1.0.0-beta',
        'version:explicit',
        'state:new',
      ],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain', 'sponsorship:sponsored'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: ['stateful', 'live-gap'],
    support: {
      level: 'offline-only',
      limitation:
        'Release deployment ignores the beta Nexus version while validator signing still selects beta addresses, so no coherent live execute fixture exists.',
      coverageRef: 'test/vectors/accounts/account-deployment.test.ts',
    },
    expected: { kind: 'success' },
    comparison: 'isolated-state',
    terminalAssertions: ['intent-completed', 'account-deployed'],
    timeoutMs: 180_000,
  }),
  directSigningScenario({
    id: 'accounts/nexus-rhinestone-release-eip7702-typed-data',
    primaryCategory: 'accounts',
    workflow: 'direct-signing',
    mode: 'sign',
    fixtureId: 'eip7702-signing',
    caseId: 'typed-data',
    axes: {
      account: [
        'nexus',
        'nexus:rhinestone-1.0.0',
        'version:explicit',
        'state:eip7702',
      ],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['sign:typed-data', 'eip7702:authorization'],
      infrastructure: ['network:offline'],
    },
    tags: ['high-risk:nexus-eip7702-signing', 'golden-vector'],
    support: {
      level: 'offline-only',
      limitation:
        'Signing uses deterministic RPC state for an EIP-7702-delegated account.',
      coverageRef: 'test/characterization/adapters/legacy-direct.test.ts',
    },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'accounts/kernel-3.1-explicit',
    primaryCategory: 'accounts',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'kernel-ecdsa',
    caseId: 'same-chain-noop',
    axes: {
      account: ['kernel', 'kernel:3.1', 'version:explicit', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain', 'calls:single'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: ['golden-vector'],
    support: { level: 'live' },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'accounts/kernel-3.2-default-version',
    primaryCategory: 'accounts',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'kernel-ecdsa',
    caseId: 'same-chain-noop',
    axes: {
      account: ['kernel', 'kernel:3.2', 'version:default', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain', 'calls:single'],
      infrastructure: ['auth:current', 'rpc:alchemy'],
    },
    tags: [],
    support: { level: 'live' },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'accounts/kernel-3.3-deploy',
    primaryCategory: 'accounts',
    workflow: 'intent',
    mode: 'execute',
    fixtureId: 'kernel-ecdsa',
    caseId: 'same-chain-noop',
    axes: {
      account: ['kernel', 'kernel:3.3', 'version:explicit', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain', 'sponsorship:sponsored'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: ['stateful'],
    support: { level: 'live' },
    expected: { kind: 'success' },
    comparison: 'isolated-state',
    terminalAssertions: ['intent-completed', 'account-deployed'],
    timeoutMs: 180_000,
  }),
  intentScenario({
    id: 'accounts/startale-new',
    primaryCategory: 'accounts',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'startale-ecdsa',
    caseId: 'same-chain-noop',
    axes: {
      account: ['startale', 'version:default', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain', 'calls:single'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: ['golden-vector'],
    support: { level: 'live' },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'accounts/hca-canonical-factory',
    primaryCategory: 'accounts',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'hca-default',
    caseId: 'same-chain-noop',
    axes: {
      account: ['hca', 'factory:default', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain', 'calls:single'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: ['live-gap', 'golden-vector'],
    support: {
      level: 'offline-only',
      limitation: 'The release live environment does not expose HCA routing.',
      coverageRef: 'src/accounts/hca.test.ts',
    },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'accounts/hca-custom-factory-default-validator',
    primaryCategory: 'accounts',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'hca-custom-factory',
    caseId: 'same-chain-noop',
    axes: {
      account: ['hca', 'factory:custom', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain', 'calls:single'],
      infrastructure: ['auth:current', 'rpc:custom-per-chain'],
    },
    tags: ['high-risk:hca-custom-factory-default-validator', 'live-gap'],
    support: {
      level: 'offline-only',
      limitation:
        'HCA custom factories are covered by encoding until routed live.',
      coverageRef: 'src/accounts/hca.test.ts',
    },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'accounts/eoa-explicit-signing',
    primaryCategory: 'accounts',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'eoa-configured',
    caseId: 'same-chain-noop',
    axes: {
      account: ['eoa', 'version:explicit', 'state:deployed'],
      owner: ['ecdsa:single', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain', 'calls:single'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: ['live-gap', 'golden-vector'],
    support: {
      level: 'offline-only',
      limitation:
        'EOA intent routing is not enabled in the shared live project.',
      coverageRef: 'src/execution/utils.test.ts',
    },
    expected: { kind: 'success' },
  }),
] as const
