import { intentScenario } from '../types'

export const failureScenarios = [
  intentScenario({
    id: 'failures/deprecated-api-key-custom-orchestrator-headers',
    primaryCategory: 'failures',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'custom-providers',
    caseId: 'same-chain-noop',
    axes: {
      account: ['nexus', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain'],
      infrastructure: [
        'auth:deprecated-api-key',
        'orchestrator:custom-url',
        'orchestrator:custom-headers',
        'rpc:custom-per-chain',
      ],
    },
    tags: ['golden-vector'],
    support: { level: 'live' },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'failures/jwt-auth-refresh',
    primaryCategory: 'failures',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'auth-jwt',
    caseId: 'same-chain-noop',
    axes: {
      account: ['safe', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain'],
      infrastructure: [
        'auth:jwt',
        'auth:jwt-refresh',
        'rpc:default',
        'orchestrator:default',
      ],
    },
    tags: ['live-gap'],
    support: {
      level: 'offline-only',
      limitation:
        'JWT integration credentials are not part of the documented harness contract.',
      coverageRef: 'src/jwt-server/jwt-server.test.ts',
    },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'failures/connection-retry-exhaustion',
    primaryCategory: 'failures',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'custom-providers',
    caseId: 'server-failure-fixture',
    axes: {
      account: ['nexus', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain'],
      infrastructure: [
        'network:offline',
        'transport:connection',
        'transport:retry',
        'failure:prepare',
      ],
    },
    tags: ['negative'],
    support: {
      level: 'offline-only',
      limitation: 'Connection retries use fake fetch and a fake clock.',
      coverageRef: 'src/orchestrator/error.test.ts',
    },
    expected: {
      kind: 'failure',
      stage: 'prepare',
      errorClass: 'TypeError',
      messageInvariant: 'fetch failed',
    },
  }),
  intentScenario({
    id: 'failures/rate-limit-retry-exhaustion',
    primaryCategory: 'failures',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'custom-providers',
    caseId: 'server-failure-fixture',
    axes: {
      account: ['nexus', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain'],
      infrastructure: [
        'network:offline',
        'transport:rate-limit',
        'transport:retry',
        'failure:prepare',
      ],
    },
    tags: ['negative'],
    support: {
      level: 'offline-only',
      limitation: 'Rate-limit retries use fake fetch and a fake clock.',
      coverageRef: 'src/orchestrator/error.test.ts',
    },
    expected: {
      kind: 'failure',
      stage: 'prepare',
      errorClass: 'RateLimitedError',
      code: 'TOO_MANY_REQUESTS',
      messageInvariant: 'rate limited',
    },
  }),
  intentScenario({
    id: 'failures/external-service-timeout',
    primaryCategory: 'failures',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'custom-providers',
    caseId: 'server-failure-fixture',
    axes: {
      account: ['nexus', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain'],
      infrastructure: [
        'network:offline',
        'transport:timeout',
        'failure:prepare',
      ],
    },
    tags: ['negative'],
    support: {
      level: 'offline-only',
      limitation: 'Timeout behavior uses fake fetch and a fake clock.',
      coverageRef: 'src/orchestrator/error.test.ts',
    },
    expected: {
      kind: 'failure',
      stage: 'prepare',
      errorClass: 'ExternalServiceTimeoutError',
      code: 'EXTERNAL_SERVICE_TIMEOUT',
      messageInvariant: 'external service timeout',
    },
  }),
  intentScenario({
    id: 'failures/jwt-auth-rejected',
    primaryCategory: 'failures',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'auth-jwt',
    caseId: 'server-failure-fixture',
    axes: {
      account: ['safe', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain'],
      infrastructure: [
        'auth:jwt',
        'auth:jwt-failure',
        'rpc:default',
        'orchestrator:default',
        'failure:prepare',
      ],
    },
    tags: ['negative', 'live-gap'],
    support: {
      level: 'offline-only',
      limitation:
        'JWT integration credentials are not part of the documented harness contract.',
      coverageRef: 'src/jwt-server/jwt-server.test.ts',
    },
    expected: {
      kind: 'failure',
      stage: 'prepare',
      errorClass: 'UnauthorizedError',
      code: 'UNAUTHORIZED',
      messageInvariant: 'unauthorized',
    },
  }),
  intentScenario({
    id: 'failures/eip7702-authorization-signer-rejected',
    primaryCategory: 'failures',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'custom-providers',
    caseId: 'missing-authorization',
    axes: {
      account: ['nexus', 'state:eip7702'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain', 'eip7702:authorization'],
      infrastructure: [
        'network:offline',
        'rpc:custom-per-chain',
        'failure:authorize',
      ],
    },
    tags: ['negative'],
    support: {
      level: 'offline-only',
      limitation: 'A deterministic signer port rejects authorization.',
      coverageRef: 'src/execution/signing.test.ts',
    },
    expected: {
      kind: 'failure',
      stage: 'authorize',
      errorClass: 'Error',
      messageInvariant: 'authorization signer rejected request',
    },
  }),
  intentScenario({
    id: 'failures/tampered-session-signature',
    primaryCategory: 'failures',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'session-single',
    caseId: 'tampered-signature',
    axes: {
      account: ['nexus', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['fresh', 'action:enable', 'action:use'],
      operation: ['intent:same-chain'],
      infrastructure: [
        'auth:current',
        'rpc:default',
        'tamper:signature',
        'failure:submit',
      ],
    },
    tags: ['negative'],
    support: { level: 'live' },
    expected: {
      kind: 'failure',
      stage: 'submit',
      errorClass: 'SimulationFailedError',
      code: 'SIMULATION_FAILED',
      messageInvariant: 'Simulation failed',
    },
  }),
  intentScenario({
    id: 'failures/tampered-prepared-quote',
    primaryCategory: 'failures',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'nexus-ecdsa',
    caseId: 'tampered-prepared-payload',
    axes: {
      account: ['nexus', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain'],
      infrastructure: ['network:offline', 'tamper:prepared', 'failure:sign'],
    },
    tags: ['negative', 'golden-vector'],
    support: {
      level: 'offline-only',
      limitation: 'Quote membership validation is local.',
      coverageRef: 'src/execution/independent-signing.test.ts',
    },
    expected: {
      kind: 'failure',
      stage: 'sign',
      errorClass: 'QuoteNotInPreparedTransactionError',
      messageInvariant:
        'Selected quote does not belong to the prepared transaction',
    },
  }),
  intentScenario({
    id: 'failures/unsupported-route-token',
    primaryCategory: 'failures',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'nexus-ecdsa',
    caseId: 'unsupported-route',
    axes: {
      account: ['nexus', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:cross-chain', 'asset:erc20'],
      infrastructure: [
        'auth:current',
        'rpc:default',
        'unsupported:route',
        'unsupported:token',
        'failure:prepare',
      ],
    },
    tags: ['negative'],
    support: { level: 'live' },
    expected: {
      kind: 'failure',
      stage: 'prepare',
      errorClass: 'UnprocessableContentError',
      code: 'UNPROCESSABLE_CONTENT',
      messageInvariant: 'not supported',
    },
  }),
  intentScenario({
    id: 'failures/unsupported-chain-account',
    primaryCategory: 'failures',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'nexus-ecdsa',
    caseId: 'unsupported-chain',
    axes: {
      account: ['nexus', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain'],
      infrastructure: [
        'network:offline',
        'unsupported:chain',
        'unsupported:account',
        'wrong-chain',
        'failure:prepare',
      ],
    },
    tags: ['negative'],
    support: {
      level: 'offline-only',
      limitation: 'Unsupported registry lookup fails before network access.',
      coverageRef: 'src/orchestrator/registry.test.ts',
    },
    expected: {
      kind: 'failure',
      stage: 'prepare',
      errorClass: 'UnsupportedChainError',
      messageInvariant: 'Unsupported chain',
    },
  }),
  intentScenario({
    id: 'failures/deliberate-live-terminal-failure',
    primaryCategory: 'failures',
    workflow: 'intent',
    mode: 'execute',
    fixtureId: 'nexus-ecdsa',
    caseId: 'terminal-failure-fixture',
    axes: {
      account: ['nexus', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:cross-chain'],
      infrastructure: [
        'auth:current',
        'rpc:default',
        'live-terminal-fixture',
        'live-server-fixture',
        'failure:execution',
      ],
    },
    tags: ['negative', 'stateful', 'live-gap'],
    support: {
      level: 'offline-only',
      limitation:
        'No documented live endpoint fixture reaches a stable terminal failure.',
      coverageRef: 'test/integration/scenarios/smoke.itest.ts',
    },
    expected: {
      kind: 'failure',
      stage: 'execution',
      errorClass: 'IntentFailedError',
      messageInvariant: 'Intent failed',
    },
    setup: {
      identity: 'ephemeral',
      preconditions: ['account-deployed', 'stable-failure-fixture'],
      funding: 'none',
      uniqueness: 'funding-lane',
      cleanup: 'none',
    },
    comparison: 'isolated-state',
    terminalAssertions: ['intent-terminal-failure'],
    timeoutMs: 180_000,
  }),
] as const
