import { intentScenario } from '../types'

export const intentScenarios = [
  intentScenario({
    id: 'intents/same-chain-native-exact',
    primaryCategory: 'intents',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'nexus-ecdsa',
    caseId: 'native-transfer',
    axes: {
      account: ['nexus', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: [
        'intent:same-chain',
        'asset:native',
        'amount:exact',
        'calls:single',
        'source-calls:none',
        'recipient:account',
      ],
      infrastructure: ['auth:current', 'rpc:default', 'orchestrator:default'],
    },
    tags: ['smoke', 'golden-vector'],
    support: { level: 'live' },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'intents/cross-chain-erc20-exact',
    primaryCategory: 'intents',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'safe-ecdsa',
    caseId: 'erc20-transfer',
    axes: {
      account: ['safe', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: [
        'intent:cross-chain',
        'asset:erc20',
        'amount:exact',
        'calls:single',
        'recipient:account',
      ],
      infrastructure: ['auth:current', 'rpc:default', 'orchestrator:default'],
    },
    tags: ['golden-vector', 'stateful'],
    support: { level: 'live' },
    expected: { kind: 'success' },
    setup: {
      identity: 'deterministic',
      preconditions: ['account-funded'],
      funding: 'erc20',
      uniqueness: 'funding-lane',
      cleanup: 'none',
    },
  }),
  intentScenario({
    id: 'intents/non-evm-symbol-amount-omitted',
    primaryCategory: 'intents',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'nexus-ecdsa',
    caseId: 'non-evm-destination',
    axes: {
      account: ['nexus', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: [
        'intent:cross-chain',
        'destination:non-evm',
        'asset:non-evm-address',
        'amount:omitted',
        'recipient:alternate',
      ],
      infrastructure: ['auth:current', 'rpc:default', 'orchestrator:default'],
    },
    tags: ['golden-vector', 'live-gap'],
    support: {
      level: 'offline-only',
      limitation:
        'Only mainnet non-EVM destinations are exposed by the release package.',
      coverageRef: 'src/orchestrator/destinations.test.ts',
    },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'intents/lazy-call-resolution-vector',
    primaryCategory: 'intents',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'kernel-ecdsa',
    caseId: 'lazy-multiple-calls',
    axes: {
      account: ['kernel', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain', 'calls:lazy-multiple'],
      infrastructure: ['auth:current', 'rpc:default', 'orchestrator:default'],
    },
    tags: ['golden-vector'],
    support: { level: 'live' },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'intents/access-list-preclaim-vector',
    primaryCategory: 'intents',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'nexus-ecdsa',
    caseId: 'preclaim',
    axes: {
      account: ['nexus', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:cross-chain', 'access-list', 'preclaim'],
      infrastructure: ['auth:current', 'rpc:default', 'orchestrator:default'],
    },
    tags: ['golden-vector', 'stateful'],
    support: { level: 'live' },
    expected: { kind: 'success' },
    setup: {
      identity: 'deterministic',
      preconditions: ['account-deployed', 'account-funded'],
      funding: 'erc20',
      uniqueness: 'funding-lane',
      cleanup: 'none',
    },
  }),
  intentScenario({
    id: 'intents/exact-chain-token-input',
    primaryCategory: 'intents',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'nexus-ecdsa',
    caseId: 'chain-token-request',
    axes: {
      account: ['nexus', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:cross-chain', 'asset:chain-token', 'amount:exact'],
      infrastructure: ['auth:current', 'rpc:default', 'orchestrator:default'],
    },
    tags: ['stateful'],
    support: { level: 'live' },
    expected: { kind: 'success' },
    setup: {
      identity: 'deterministic',
      preconditions: ['account-funded'],
      funding: 'erc20',
      uniqueness: 'funding-lane',
      cleanup: 'none',
    },
  }),
  intentScenario({
    id: 'intents/erc20-amount-omitted',
    primaryCategory: 'intents',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'safe-ecdsa',
    caseId: 'amount-omitted-request',
    axes: {
      account: ['safe', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:cross-chain', 'asset:erc20', 'amount:omitted'],
      infrastructure: ['auth:current', 'rpc:default', 'orchestrator:default'],
    },
    tags: ['stateful'],
    support: { level: 'live' },
    expected: { kind: 'success' },
    setup: {
      identity: 'deterministic',
      preconditions: ['account-funded'],
      funding: 'erc20',
      uniqueness: 'funding-lane',
      cleanup: 'none',
    },
  }),
  intentScenario({
    id: 'intents/multiple-destination-calls',
    primaryCategory: 'intents',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'safe-ecdsa',
    caseId: 'multiple-calls',
    axes: {
      account: ['safe', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain', 'calls:multiple'],
      infrastructure: ['auth:current', 'rpc:default', 'orchestrator:default'],
    },
    tags: [],
    support: { level: 'live' },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'intents/lazy-single-call',
    primaryCategory: 'intents',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'kernel-ecdsa',
    caseId: 'lazy-single-call',
    axes: {
      account: ['kernel', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain', 'calls:lazy-single'],
      infrastructure: ['auth:current', 'rpc:default', 'orchestrator:default'],
    },
    tags: [],
    support: { level: 'live' },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'intents/lazy-multiple-calls',
    primaryCategory: 'intents',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'kernel-ecdsa',
    caseId: 'lazy-multiple-calls',
    axes: {
      account: ['kernel', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:cross-chain', 'calls:lazy-multiple'],
      infrastructure: ['auth:current', 'rpc:default', 'orchestrator:default'],
    },
    tags: [],
    support: { level: 'live' },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'intents/source-call-without-declared-funds',
    primaryCategory: 'intents',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'nexus-ecdsa',
    caseId: 'source-call-without-funds',
    axes: {
      account: ['nexus', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: [
        'intent:cross-chain',
        'source-calls:without-funds',
        'asset:erc20',
      ],
      infrastructure: ['auth:current', 'rpc:default', 'orchestrator:default'],
    },
    tags: ['stateful'],
    support: { level: 'live' },
    expected: { kind: 'success' },
    setup: {
      identity: 'deterministic',
      preconditions: ['account-deployed', 'account-funded'],
      funding: 'erc20',
      uniqueness: 'funding-lane',
      cleanup: 'none',
    },
  }),
  intentScenario({
    id: 'intents/source-call-funds-cross-chain-token',
    primaryCategory: 'intents',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'nexus-ecdsa',
    caseId: 'source-call-with-funds',
    axes: {
      account: ['nexus', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: [
        'intent:cross-chain',
        'source-calls:with-funds',
        'asset:chain-token',
        'amount:exact',
      ],
      infrastructure: ['auth:current', 'rpc:default', 'orchestrator:default'],
    },
    tags: ['high-risk:source-call-funds-cross-chain-token'],
    support: {
      level: 'offline-only',
      limitation:
        'No live source call that deterministically produces testnet USDC is configured.',
      coverageRef: 'src/execution/utils.test.ts',
    },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'intents/alternate-recipient',
    primaryCategory: 'intents',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'safe-ecdsa',
    caseId: 'alternate-recipient',
    axes: {
      account: ['safe', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:cross-chain', 'recipient:alternate', 'asset:symbol'],
      infrastructure: ['auth:current', 'rpc:default', 'orchestrator:default'],
    },
    tags: ['stateful'],
    support: { level: 'live' },
    expected: { kind: 'success' },
    setup: {
      identity: 'deterministic',
      preconditions: ['account-funded'],
      funding: 'erc20',
      uniqueness: 'funding-lane',
      cleanup: 'none',
    },
  }),
  intentScenario({
    id: 'intents/app-fee-input',
    primaryCategory: 'intents',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'nexus-ecdsa',
    caseId: 'app-fee',
    axes: {
      account: ['nexus', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:cross-chain', 'app-fee', 'asset:erc20'],
      infrastructure: ['auth:current', 'rpc:default', 'orchestrator:default'],
    },
    tags: ['stateful'],
    support: { level: 'live' },
    expected: { kind: 'success' },
    setup: {
      identity: 'deterministic',
      preconditions: ['account-funded'],
      funding: 'erc20',
      uniqueness: 'funding-lane',
      cleanup: 'none',
    },
  }),
  intentScenario({
    id: 'intents/settlement-layer-filter',
    primaryCategory: 'intents',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'nexus-ecdsa',
    caseId: 'settlement-filter',
    axes: {
      account: ['nexus', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:cross-chain', 'settlement-filter', 'asset:symbol'],
      infrastructure: ['auth:current', 'rpc:default', 'orchestrator:default'],
    },
    tags: ['stateful'],
    support: { level: 'live' },
    expected: { kind: 'success' },
    setup: {
      identity: 'deterministic',
      preconditions: ['account-funded'],
      funding: 'erc20',
      uniqueness: 'funding-lane',
      cleanup: 'none',
    },
  }),
  intentScenario({
    id: 'intents/execute-sponsored-native',
    primaryCategory: 'intents',
    workflow: 'intent',
    mode: 'execute',
    fixtureId: 'nexus-ecdsa',
    caseId: 'native-transfer',
    axes: {
      account: ['nexus', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain', 'asset:native', 'sponsorship:sponsored'],
      infrastructure: ['auth:current', 'rpc:default', 'orchestrator:default'],
    },
    tags: ['stateful'],
    support: { level: 'live' },
    expected: { kind: 'success' },
    setup: {
      identity: 'ephemeral',
      preconditions: ['account-deployed', 'account-funded'],
      funding: 'native',
      uniqueness: 'funding-lane',
      cleanup: 'none',
    },
    comparison: 'isolated-state',
    terminalAssertions: ['intent-completed', 'balance-changed'],
    timeoutMs: 180_000,
  }),
  intentScenario({
    id: 'intents/execute-unsponsored-erc20',
    primaryCategory: 'intents',
    workflow: 'intent',
    mode: 'execute',
    fixtureId: 'safe-ecdsa',
    caseId: 'erc20-transfer',
    axes: {
      account: ['safe', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: [
        'intent:same-chain',
        'asset:erc20',
        'sponsorship:unsponsored',
      ],
      infrastructure: ['auth:current', 'rpc:default', 'orchestrator:default'],
    },
    tags: ['stateful'],
    support: { level: 'live' },
    expected: { kind: 'success' },
    setup: {
      identity: 'ephemeral',
      preconditions: ['account-deployed', 'account-funded'],
      funding: 'erc20',
      uniqueness: 'funding-lane',
      cleanup: 'none',
    },
    comparison: 'isolated-state',
    terminalAssertions: ['intent-completed', 'balance-changed'],
    timeoutMs: 180_000,
  }),
  intentScenario({
    id: 'intents/execute-multiple-calls',
    primaryCategory: 'intents',
    workflow: 'intent',
    mode: 'execute',
    fixtureId: 'kernel-ecdsa',
    caseId: 'multiple-calls',
    axes: {
      account: ['kernel', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: [
        'intent:same-chain',
        'calls:multiple',
        'sponsorship:sponsored',
      ],
      infrastructure: ['auth:current', 'rpc:default', 'orchestrator:default'],
    },
    tags: ['stateful'],
    support: { level: 'live' },
    expected: { kind: 'success' },
    comparison: 'isolated-state',
    terminalAssertions: ['intent-completed', 'no-failed-operations'],
    timeoutMs: 180_000,
  }),
  intentScenario({
    id: 'intents/convenience-send',
    primaryCategory: 'intents',
    workflow: 'intent',
    mode: 'execute',
    fixtureId: 'nexus-ecdsa',
    caseId: 'send-convenience',
    axes: {
      account: ['nexus', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: [
        'intent:same-chain',
        'flow:send-convenience',
        'sponsorship:sponsored',
      ],
      infrastructure: ['auth:current', 'rpc:default', 'orchestrator:default'],
    },
    tags: ['stateful', 'live-gap'],
    support: {
      level: 'offline-only',
      limitation: 'Release has no public convenience send method.',
      coverageRef:
        'test/characterization/adapters/legacy-gap-contracts.test.ts',
    },
    expected: { kind: 'success' },
    comparison: 'isolated-state',
    terminalAssertions: ['intent-completed', 'account-deployed'],
    timeoutMs: 180_000,
  }),
  intentScenario({
    id: 'intents/execute-cross-chain-token',
    primaryCategory: 'intents',
    workflow: 'intent',
    mode: 'execute',
    fixtureId: 'nexus-ecdsa',
    caseId: 'symbol-request',
    axes: {
      account: ['nexus', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: [
        'intent:cross-chain',
        'asset:symbol',
        'amount:exact',
        'sponsorship:sponsored',
      ],
      infrastructure: ['auth:current', 'rpc:default', 'orchestrator:default'],
    },
    tags: ['stateful'],
    support: { level: 'live' },
    expected: { kind: 'success' },
    setup: {
      identity: 'ephemeral',
      preconditions: ['account-deployed', 'account-funded'],
      funding: 'erc20',
      uniqueness: 'funding-lane',
      cleanup: 'none',
    },
    comparison: 'isolated-state',
    terminalAssertions: ['intent-completed', 'balance-changed'],
    // Cross-chain execute waits on relayer settlement, whose fill latency on dev
    // is highly variable (seconds typically, but occasional multi-minute stalls).
    timeoutMs: 300_000,
  }),
] as const
