import { directSigningScenario, intentScenario } from '../types'

export const sessionScenarios = [
  intentScenario({
    id: 'sessions/fresh-inline-enable',
    primaryCategory: 'sessions',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'session-single',
    caseId: 'enable-and-use-session',
    axes: {
      account: ['kernel', 'kernel:3.3', 'version:explicit', 'state:new'],
      owner: ['ecdsa:single', 'validator:default'],
      session: [
        'fresh',
        'signers:single',
        'action:enable',
        'action:use',
        'contracts:development',
      ],
      operation: ['intent:same-chain', 'calls:single'],
      infrastructure: ['auth:current', 'rpc:default', 'contracts:development'],
    },
    tags: ['smoke', 'high-risk:kernel-version-session-enable-use'],
    support: { level: 'live' },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'sessions/enabled-use-erc1271',
    primaryCategory: 'sessions',
    workflow: 'intent',
    mode: 'execute',
    fixtureId: 'session-single',
    caseId: 'session-erc1271',
    axes: {
      account: ['nexus', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default'],
      session: [
        'enabled',
        'signers:single',
        'action:use',
        'action:erc1271',
        'contracts:development',
      ],
      operation: [
        'intent:same-chain',
        'verify:erc1271',
        'sponsorship:sponsored',
      ],
      infrastructure: ['auth:current', 'rpc:default', 'contracts:development'],
    },
    tags: ['stateful'],
    support: { level: 'live' },
    expected: { kind: 'success' },
    setup: {
      identity: 'ephemeral',
      preconditions: ['account-deployed', 'session-enabled'],
      funding: 'none',
      uniqueness: 'funding-lane',
      cleanup: 'disable-session',
    },
    comparison: 'isolated-state',
    terminalAssertions: ['intent-completed'],
    timeoutMs: 180_000,
  }),
  intentScenario({
    id: 'sessions/fresh-claim-only-artifact',
    primaryCategory: 'sessions',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'session-single',
    caseId: 'claim-only-session',
    axes: {
      account: ['nexus', 'state:new'],
      owner: ['ecdsa:single', 'validator:default'],
      session: [
        'fresh',
        'claim:fresh-only',
        'signers:single',
        'contracts:production',
      ],
      operation: ['intent:same-chain'],
      infrastructure: ['network:offline', 'contracts:production'],
    },
    tags: ['golden-vector'],
    support: {
      level: 'offline-only',
      limitation: 'Claim artifact is a local vector.',
      coverageRef: 'src/execution/utils.test.ts',
    },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'sessions/enabled-claim-only-artifact',
    primaryCategory: 'sessions',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'session-single',
    caseId: 'claim-only-session',
    axes: {
      account: ['nexus', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default'],
      session: ['enabled', 'claim:enabled-only', 'signers:single'],
      operation: ['intent:same-chain'],
      infrastructure: ['network:offline'],
    },
    tags: ['golden-vector'],
    support: {
      level: 'offline-only',
      limitation: 'Claim artifact is a local vector.',
      coverageRef: 'src/execution/utils.test.ts',
    },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'sessions/single-session-signer-set',
    primaryCategory: 'sessions',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'session-single',
    caseId: 'use-enabled-session',
    axes: {
      account: ['safe', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default'],
      session: ['enabled', 'signers:single', 'permission:sudo'],
      operation: ['intent:same-chain'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: [],
    support: { level: 'live' },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'sessions/per-chain-signers-and-owners',
    primaryCategory: 'sessions',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'session-per-chain',
    caseId: 'cross-chain-noop',
    axes: {
      account: ['nexus', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default'],
      session: [
        'enabled',
        'signers:per-chain',
        'owners:per-chain',
        'destination:explicit',
      ],
      operation: ['intent:cross-chain'],
      infrastructure: ['auth:current', 'rpc:custom-per-chain'],
    },
    tags: [],
    support: { level: 'live' },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'sessions/per-chain-origin-destination-asymmetry',
    primaryCategory: 'sessions',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'session-per-chain',
    caseId: 'cross-chain-noop',
    axes: {
      account: ['safe', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default'],
      session: [
        'enabled',
        'signers:per-chain',
        'owners:per-chain',
        'destination:explicit',
      ],
      operation: ['intent:cross-chain'],
      infrastructure: ['auth:current', 'rpc:custom-per-chain'],
    },
    tags: ['high-risk:per-chain-session-asymmetry'],
    support: { level: 'live' },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'sessions/non-evm-destination-reuse-headless',
    primaryCategory: 'sessions',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'session-cross-chain',
    caseId: 'session-headless-sign',
    axes: {
      account: ['nexus', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default'],
      session: [
        'enabled',
        'destination:non-evm-reuse',
        'destination:reuse',
        'action:headless-sign-intent',
      ],
      operation: ['intent:cross-chain', 'destination:non-evm'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: ['golden-vector', 'live-gap'],
    support: {
      level: 'offline-only',
      limitation:
        'Only mainnet non-EVM destinations are exposed by the release package.',
      coverageRef: 'src/orchestrator/destinations.test.ts',
    },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'sessions/owner-only-intent',
    primaryCategory: 'sessions',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'session-single',
    caseId: 'same-chain-noop',
    axes: {
      account: ['nexus', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['owner-only'],
      operation: ['intent:same-chain'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: [],
    support: { level: 'live' },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'sessions/destination-signature-reuse',
    primaryCategory: 'sessions',
    workflow: 'intent',
    mode: 'execute',
    fixtureId: 'nexus-ecdsa',
    caseId: 'cross-chain-noop',
    axes: {
      account: ['nexus', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default'],
      session: ['none', 'destination:reuse'],
      operation: ['intent:cross-chain', 'sponsorship:sponsored'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: ['stateful'],
    support: { level: 'live' },
    expected: { kind: 'success' },
    setup: {
      identity: 'ephemeral',
      preconditions: ['account-deployed'],
      funding: 'none',
      uniqueness: 'funding-lane',
      cleanup: 'none',
    },
    comparison: 'isolated-state',
    terminalAssertions: ['intent-completed'],
    // Cross-chain execute waits on variable relayer settlement latency.
    timeoutMs: 300_000,
  }),
  intentScenario({
    id: 'sessions/startale-cross-chain-destination-signing',
    primaryCategory: 'sessions',
    workflow: 'intent',
    mode: 'execute',
    fixtureId: 'session-cross-chain',
    caseId: 'cross-chain-noop',
    axes: {
      account: ['startale', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default'],
      session: ['enabled', 'destination:explicit', 'signers:per-chain'],
      operation: ['intent:cross-chain', 'sponsorship:sponsored'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: ['high-risk:startale-cross-chain-destination-signing', 'stateful'],
    support: { level: 'live' },
    expected: { kind: 'success' },
    setup: {
      identity: 'ephemeral',
      preconditions: ['account-deployed', 'session-enabled'],
      funding: 'none',
      uniqueness: 'funding-lane',
      cleanup: 'none',
    },
    comparison: 'isolated-state',
    terminalAssertions: ['intent-completed'],
    // Cross-chain execute waits on variable relayer settlement latency.
    timeoutMs: 300_000,
  }),
  intentScenario({
    id: 'sessions/sudo-permission',
    primaryCategory: 'sessions',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'session-policy',
    caseId: 'use-enabled-session',
    axes: {
      account: ['nexus', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default'],
      session: ['enabled', 'permission:sudo', 'action:use'],
      operation: ['intent:same-chain'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: [],
    support: { level: 'live' },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'sessions/scoped-permission',
    primaryCategory: 'sessions',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'session-policy',
    caseId: 'use-enabled-session',
    axes: {
      account: ['safe', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default'],
      session: ['enabled', 'permission:scoped', 'selector:valid'],
      operation: ['intent:same-chain'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: [],
    support: { level: 'live' },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'sessions/fallback-permission',
    primaryCategory: 'sessions',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'session-policy',
    caseId: 'use-enabled-session',
    axes: {
      account: ['kernel', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default'],
      session: ['enabled', 'permission:fallback'],
      operation: ['intent:same-chain'],
      infrastructure: ['network:offline'],
    },
    tags: ['golden-vector'],
    support: {
      level: 'offline-only',
      limitation: 'Fallback permission encoding is local.',
      coverageRef: 'src/modules/validators/permissions.test.ts',
    },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'sessions/abi-derived-permission',
    primaryCategory: 'sessions',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'session-policy',
    caseId: 'use-enabled-session',
    axes: {
      account: ['nexus', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default'],
      session: ['enabled', 'permission:abi', 'selector:valid'],
      operation: ['intent:same-chain'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: [],
    support: { level: 'live' },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'sessions/universal-action-argument-expression',
    primaryCategory: 'sessions',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'session-policy',
    caseId: 'use-enabled-session',
    axes: {
      account: ['nexus', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default'],
      session: [
        'enabled',
        'policy:universal-action',
        'policy:argument-expression',
        'calldata-offset:valid',
      ],
      operation: ['intent:same-chain'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: [],
    support: { level: 'live' },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'sessions/spending-and-usage-policy',
    primaryCategory: 'sessions',
    workflow: 'intent',
    mode: 'execute',
    fixtureId: 'session-policy',
    caseId: 'use-enabled-session',
    axes: {
      account: ['nexus', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default'],
      session: ['enabled', 'policy:spending', 'policy:usage', 'limit:valid'],
      operation: ['intent:same-chain', 'sponsorship:sponsored'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: ['stateful'],
    support: { level: 'live' },
    expected: { kind: 'success' },
    setup: {
      identity: 'ephemeral',
      preconditions: ['account-deployed', 'session-enabled', 'account-funded'],
      funding: 'erc20',
      uniqueness: 'funding-lane',
      cleanup: 'none',
    },
    comparison: 'isolated-state',
    terminalAssertions: ['intent-completed'],
    timeoutMs: 180_000,
  }),
  intentScenario({
    id: 'sessions/timeframe-value-intent-policy',
    primaryCategory: 'sessions',
    workflow: 'intent',
    mode: 'execute',
    fixtureId: 'session-policy',
    caseId: 'use-enabled-session',
    axes: {
      account: ['safe', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default'],
      session: [
        'enabled',
        'policy:timeframe',
        'policy:value',
        'policy:intent-execution',
        'window:valid',
      ],
      operation: ['intent:same-chain', 'sponsorship:sponsored'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: ['stateful'],
    support: { level: 'live' },
    expected: { kind: 'success' },
    setup: {
      identity: 'ephemeral',
      preconditions: ['account-deployed', 'session-enabled'],
      funding: 'none',
      uniqueness: 'funding-lane',
      cleanup: 'none',
    },
    comparison: 'isolated-state',
    terminalAssertions: ['intent-completed'],
    timeoutMs: 180_000,
  }),
  intentScenario({
    id: 'sessions/valid-window-limit-selector-offset',
    primaryCategory: 'sessions',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'session-policy',
    caseId: 'use-enabled-session',
    axes: {
      account: ['nexus', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default'],
      session: [
        'enabled',
        'window:valid',
        'limit:valid',
        'selector:valid',
        'calldata-offset:valid',
      ],
      operation: ['intent:same-chain'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: [],
    support: { level: 'live' },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'sessions/invalid-window-limit-selector-offset',
    primaryCategory: 'sessions',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'session-policy',
    caseId: 'invalid-policy',
    axes: {
      account: ['nexus', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default'],
      session: [
        'enabled',
        'window:invalid',
        'limit:invalid',
        'selector:invalid',
        'calldata-offset:invalid',
      ],
      operation: ['intent:same-chain'],
      infrastructure: ['network:offline', 'failure:prepare'],
    },
    tags: ['negative'],
    support: {
      level: 'offline-only',
      limitation: 'Invalid policy validation is local.',
      coverageRef: 'src/modules/validators/permissions.test.ts',
    },
    expected: {
      kind: 'failure',
      stage: 'prepare',
      errorClass: 'Error',
      messageInvariant: 'validUntil is before validAfter',
    },
  }),
  intentScenario({
    id: 'sessions/cross-chain-permit-claim-recipient-override',
    primaryCategory: 'sessions',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'session-cross-chain',
    caseId: 'cross-chain-permit',
    axes: {
      account: ['nexus', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default'],
      session: [
        'enabled',
        'permit:cross-chain',
        'policy:permit2-claim',
        'recipient:override',
        'settlement:subset',
        'contracts:development',
      ],
      operation: ['intent:cross-chain', 'recipient:alternate', 'preclaim'],
      infrastructure: [
        'auth:current',
        'rpc:custom-per-chain',
        'contracts:development',
      ],
    },
    tags: ['high-risk:cross-chain-permit-claim-recipient', 'negative'],
    support: { level: 'live' },
    expected: {
      kind: 'failure',
      stage: 'submit',
      errorClass: 'SimulationFailedError',
      code: 'SIMULATION_FAILED',
      messageInvariant: 'UnclassifiedRevert',
    },
    setup: {
      identity: 'ephemeral',
      preconditions: ['account-deployed', 'session-enabled', 'account-funded'],
      funding: 'erc20',
      uniqueness: 'funding-lane',
      cleanup: 'none',
    },
  }),
  intentScenario({
    id: 'sessions/bridge-self-all-settlement-layers',
    primaryCategory: 'sessions',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'session-cross-chain',
    caseId: 'cross-chain-permit',
    axes: {
      account: ['nexus', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default'],
      session: [
        'enabled',
        'permit:cross-chain',
        'recipient:bridge-self',
        'settlement:all',
      ],
      operation: ['intent:cross-chain', 'recipient:account'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: ['golden-vector'],
    support: { level: 'live' },
    expected: { kind: 'success' },
    setup: {
      identity: 'ephemeral',
      preconditions: ['account-deployed', 'session-enabled', 'account-funded'],
      funding: 'erc20',
      uniqueness: 'funding-lane',
      cleanup: 'none',
    },
  }),
  intentScenario({
    id: 'sessions/disable-enabled-session',
    primaryCategory: 'sessions',
    workflow: 'intent',
    mode: 'execute',
    fixtureId: 'session-single',
    caseId: 'disable-session',
    axes: {
      account: ['nexus', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default'],
      session: ['enabled', 'action:disable'],
      operation: ['intent:same-chain', 'sponsorship:sponsored'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: ['stateful'],
    support: { level: 'live' },
    expected: { kind: 'success' },
    setup: {
      identity: 'ephemeral',
      preconditions: ['account-deployed', 'session-enabled'],
      funding: 'none',
      uniqueness: 'funding-lane',
      cleanup: 'none',
    },
    comparison: 'isolated-state',
    terminalAssertions: ['intent-completed', 'session-disabled'],
    timeoutMs: 180_000,
  }),
  directSigningScenario({
    id: 'sessions/public-independent-owner-signing-rejected',
    primaryCategory: 'sessions',
    workflow: 'direct-signing',
    mode: 'sign',
    fixtureId: 'session-signing',
    caseId: 'session-independent-rejection',
    axes: {
      account: ['nexus', 'state:deployed'],
      owner: ['ecdsa:single', 'signing:independent'],
      session: ['enabled', 'independent-owner-signing:rejected'],
      operation: ['sign:typed-data'],
      infrastructure: ['network:offline', 'failure:sign'],
    },
    tags: ['negative', 'golden-vector'],
    support: {
      level: 'offline-only',
      limitation: 'The calibrated rejection occurs before network access.',
      coverageRef: 'src/execution/independent-signing.test.ts',
    },
    expected: {
      kind: 'failure',
      stage: 'sign',
      errorClass: 'IndependentSigningNotSupportedError',
      messageInvariant: 'smart sessions',
    },
  }),
] as const
