import { directSigningScenario, userOperationScenario } from '../types'

export const userOperationAndDirectSigningScenarios = [
  userOperationScenario({
    id: 'user-operations/entrypoint-0.7-sponsored-prepare-sign',
    primaryCategory: 'user-operations-and-direct-signing',
    workflow: 'user-operation',
    mode: 'sign',
    fixtureId: 'safe-user-operation-paymaster',
    caseId: 'sponsored',
    axes: {
      account: ['safe', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: [
        'userop:entrypoint-0.7',
        'userop:prepare',
        'userop:sign',
        'userop:sponsored',
      ],
      infrastructure: ['rpc:default', 'bundler:default', 'paymaster:default'],
    },
    tags: ['live-gap'],
    support: {
      level: 'offline-only',
      limitation: 'No calibrated live paymaster endpoint is configured.',
      coverageRef: 'src/transactions/user-operations/workflow.test.ts',
    },
    expected: { kind: 'success' },
  }),
  userOperationScenario({
    id: 'user-operations/unsponsored-nonce-key',
    primaryCategory: 'user-operations-and-direct-signing',
    workflow: 'user-operation',
    mode: 'sign',
    fixtureId: 'kernel-user-operation-no-paymaster',
    caseId: 'nonce-key',
    axes: {
      account: ['kernel', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: [
        'userop:entrypoint-0.7',
        'userop:prepare',
        'userop:sign',
        'userop:unsponsored',
        'userop:nonce-key',
      ],
      infrastructure: ['rpc:default', 'bundler:default', 'paymaster:default'],
    },
    tags: ['live-gap'],
    support: {
      level: 'offline-only',
      limitation: 'No calibrated live bundler endpoint is configured.',
      coverageRef: 'src/transactions/user-operations/workflow.test.ts',
    },
    expected: { kind: 'success' },
  }),
  userOperationScenario({
    id: 'user-operations/custom-bundler-paymaster-wallet-switch',
    primaryCategory: 'user-operations-and-direct-signing',
    workflow: 'user-operation',
    mode: 'sign',
    fixtureId: 'custom-user-operation-providers',
    caseId: 'prepare-and-sign',
    axes: {
      account: ['nexus', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: [
        'userop:entrypoint-0.7',
        'userop:prepare',
        'userop:sign',
        'wallet-chain:switch',
      ],
      infrastructure: [
        'rpc:custom-per-chain',
        'bundler:custom',
        'paymaster:custom',
      ],
    },
    tags: ['live-gap'],
    support: {
      level: 'offline-only',
      limitation:
        'Custom bundler and paymaster endpoints require deterministic port fixtures.',
      coverageRef: 'src/transactions/user-operations/workflow.test.ts',
    },
    expected: { kind: 'success' },
  }),
  userOperationScenario({
    id: 'user-operations/submit-sponsored-receipt',
    primaryCategory: 'user-operations-and-direct-signing',
    workflow: 'user-operation',
    mode: 'execute',
    fixtureId: 'nexus-user-operation-paymaster',
    caseId: 'submit-and-receipt',
    axes: {
      account: ['nexus', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: [
        'userop:entrypoint-0.7',
        'userop:prepare',
        'userop:sign',
        'userop:submit',
        'userop:sponsored',
      ],
      infrastructure: ['rpc:default', 'bundler:default', 'paymaster:default'],
    },
    tags: ['stateful', 'live-gap'],
    support: {
      level: 'offline-only',
      limitation:
        'No calibrated live bundler and paymaster endpoints are configured.',
      coverageRef: 'src/transactions/user-operations/workflow.test.ts',
    },
    expected: { kind: 'success' },
    comparison: 'isolated-state',
    terminalAssertions: ['user-operation-receipt-success', 'account-deployed'],
    timeoutMs: 180_000,
  }),
  userOperationScenario({
    id: 'user-operations/already-used-nonce',
    primaryCategory: 'user-operations-and-direct-signing',
    workflow: 'user-operation',
    mode: 'execute',
    fixtureId: 'safe-user-operation-paymaster',
    caseId: 'nonce-already-used',
    axes: {
      account: ['safe', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: [
        'userop:entrypoint-0.7',
        'userop:submit',
        'userop:nonce-used',
      ],
      infrastructure: [
        'rpc:default',
        'bundler:default',
        'paymaster:default',
        'failure:submit',
      ],
    },
    tags: ['negative', 'stateful', 'live-gap'],
    support: {
      level: 'offline-only',
      limitation:
        'The bundler nonce error has not been calibrated against a live endpoint.',
      coverageRef: 'src/transactions/user-operations/workflow.test.ts',
    },
    expected: {
      kind: 'failure',
      stage: 'submit',
      errorClass: 'RpcRequestError',
      messageInvariant: 'AA25 invalid account nonce',
    },
    setup: {
      identity: 'ephemeral',
      preconditions: ['account-deployed'],
      funding: 'none',
      uniqueness: 'funding-lane',
      cleanup: 'none',
    },
    comparison: 'isolated-state',
    terminalAssertions: ['user-operation-receipt-failure'],
    timeoutMs: 180_000,
  }),
  directSigningScenario({
    id: 'direct-signing/plain-message-selected-chain',
    primaryCategory: 'user-operations-and-direct-signing',
    workflow: 'direct-signing',
    mode: 'sign',
    fixtureId: 'safe-signing',
    caseId: 'plain-message',
    axes: {
      account: ['safe', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['sign:message', 'wallet-chain:selected'],
      infrastructure: ['rpc:default'],
    },
    tags: ['golden-vector'],
    support: {
      level: 'offline-only',
      limitation:
        'The case asserts signing and wallet-chain invocation, not on-chain ERC-1271 verification.',
      coverageRef: 'test/characterization/adapters/legacy-direct.test.ts',
    },
    expected: { kind: 'success' },
  }),
  directSigningScenario({
    id: 'direct-signing/typed-data-wallet-switch',
    primaryCategory: 'user-operations-and-direct-signing',
    workflow: 'direct-signing',
    mode: 'sign',
    fixtureId: 'nexus-signing',
    caseId: 'typed-data',
    axes: {
      account: ['nexus', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['sign:typed-data', 'wallet-chain:switch'],
      infrastructure: ['rpc:default'],
    },
    tags: ['golden-vector'],
    support: {
      level: 'offline-only',
      limitation:
        'The case asserts signing and wallet-chain switching, not on-chain ERC-1271 verification.',
      coverageRef: 'test/characterization/adapters/legacy-direct.test.ts',
    },
    expected: { kind: 'success' },
  }),
  directSigningScenario({
    id: 'direct-signing/nested-typed-data-numeric-coercion',
    primaryCategory: 'user-operations-and-direct-signing',
    workflow: 'direct-signing',
    mode: 'sign',
    fixtureId: 'kernel-signing',
    caseId: 'nested-typed-data',
    axes: {
      account: ['kernel', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['sign:typed-data', 'typed:nested', 'typed:numeric-coercion'],
      infrastructure: ['network:offline'],
    },
    tags: ['golden-vector'],
    support: {
      level: 'offline-only',
      limitation: 'Typed-data hashing is deterministic locally.',
      coverageRef: 'src/execution/utils.test.ts',
    },
    expected: { kind: 'success' },
  }),
  directSigningScenario({
    id: 'direct-signing/deployless-erc6492-erc1271',
    primaryCategory: 'user-operations-and-direct-signing',
    workflow: 'direct-signing',
    mode: 'sign',
    fixtureId: 'safe-signing',
    caseId: 'erc6492-verification',
    axes: {
      account: ['safe', 'state:new'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['sign:message', 'verify:erc6492', 'verify:erc1271'],
      infrastructure: ['network:offline'],
    },
    tags: ['high-risk:deployless-erc6492-erc1271', 'golden-vector'],
    support: {
      level: 'offline-only',
      limitation: 'Deployless signature wrapping is deterministic locally.',
      coverageRef: 'src/execution/signing.test.ts',
    },
    expected: { kind: 'success' },
  }),
  directSigningScenario({
    id: 'direct-signing/startale-erc7739',
    primaryCategory: 'user-operations-and-direct-signing',
    workflow: 'direct-signing',
    mode: 'sign',
    fixtureId: 'startale-signing',
    caseId: 'erc7739-verification',
    axes: {
      account: ['startale', 'state:deployed'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['sign:typed-data', 'verify:erc7739'],
      infrastructure: ['network:offline'],
    },
    tags: ['golden-vector'],
    support: {
      level: 'offline-only',
      limitation: 'ERC-7739 hashing is deterministic locally.',
      coverageRef: 'src/execution/utils.test.ts',
    },
    expected: { kind: 'success' },
  }),
  directSigningScenario({
    id: 'direct-signing/eip7702-authorization-init',
    primaryCategory: 'user-operations-and-direct-signing',
    workflow: 'direct-signing',
    mode: 'sign',
    fixtureId: 'eip7702-signing',
    caseId: 'eip7702-authorization',
    axes: {
      account: ['nexus', 'state:eip7702'],
      owner: ['ecdsa:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: [
        'eip7702:authorization',
        'eip7702:init',
        'wallet-chain:selected',
      ],
      infrastructure: ['network:offline'],
    },
    tags: ['golden-vector'],
    support: {
      level: 'offline-only',
      limitation: 'Authorization signing is deterministic locally.',
      coverageRef: 'src/execution/signing.test.ts',
    },
    expected: { kind: 'success' },
  }),
  directSigningScenario({
    id: 'direct-signing/independent-contribution-artifact',
    primaryCategory: 'user-operations-and-direct-signing',
    workflow: 'direct-signing',
    mode: 'sign',
    fixtureId: 'independent-signing',
    caseId: 'independent-contribution',
    axes: {
      account: ['safe', 'state:deployed'],
      owner: [
        'ecdsa:multi-threshold-many',
        'signing:independent',
        'owner-order:permuted',
      ],
      session: ['none'],
      operation: ['sign:typed-data'],
      infrastructure: ['network:offline'],
    },
    tags: ['golden-vector'],
    support: {
      level: 'offline-only',
      limitation: 'Contribution assembly is deterministic locally.',
      coverageRef: 'src/execution/independent-signing.test.ts',
    },
    expected: { kind: 'success' },
  }),
] as const
