import { intentScenario } from '../types'

export const validatorScenarios = [
  intentScenario({
    id: 'validators/ecdsa-single-full-signing',
    primaryCategory: 'validators',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'safe-ecdsa',
    caseId: 'same-chain-noop',
    axes: {
      account: ['safe', 'state:new'],
      owner: [
        'ecdsa:single',
        'threshold:min',
        'validator:default',
        'signing:full',
      ],
      session: ['none'],
      operation: ['intent:same-chain', 'calls:single'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: ['smoke'],
    support: { level: 'live' },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'validators/ecdsa-multi-threshold-one',
    primaryCategory: 'validators',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'safe-threshold',
    caseId: 'same-chain-noop',
    axes: {
      account: ['safe', 'state:new'],
      owner: ['ecdsa:multi-threshold-one', 'threshold:min', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain', 'calls:single'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: [],
    support: { level: 'live' },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'validators/deployed-safe-threshold-independent-signing',
    primaryCategory: 'validators',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'safe-threshold',
    caseId: 'same-chain-noop',
    axes: {
      account: ['safe', 'safe:1.4.1', 'state:deployed'],
      owner: [
        'ecdsa:multi-threshold-many',
        'threshold:max',
        'signing:independent',
      ],
      session: ['none'],
      operation: ['intent:same-chain', 'flow:prepare-sign-submit'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: ['high-risk:deployed-safe-threshold-independent', 'golden-vector'],
    support: { level: 'live' },
    expected: { kind: 'success' },
    setup: {
      identity: 'deterministic',
      preconditions: ['account-deployed'],
      funding: 'none',
      uniqueness: 'scenario-id',
      cleanup: 'none',
    },
  }),
  intentScenario({
    id: 'validators/ecdsa-multi-threshold-execute',
    primaryCategory: 'validators',
    workflow: 'intent',
    mode: 'execute',
    fixtureId: 'safe-threshold',
    caseId: 'same-chain-noop',
    axes: {
      account: ['safe', 'state:new'],
      owner: ['ecdsa:multi-threshold-many', 'threshold:max', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain', 'sponsorship:sponsored'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: ['stateful'],
    support: { level: 'live' },
    expected: { kind: 'success' },
    comparison: 'isolated-state',
    terminalAssertions: ['intent-completed', 'account-deployed'],
    timeoutMs: 180_000,
  }),
  intentScenario({
    id: 'validators/ens-owner-unexpired',
    primaryCategory: 'validators',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'hca-ens',
    caseId: 'same-chain-noop',
    axes: {
      account: ['hca', 'state:new'],
      owner: ['ens:unexpired', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain', 'calls:single'],
      infrastructure: ['network:offline'],
    },
    tags: ['live-gap', 'golden-vector'],
    support: {
      level: 'offline-only',
      limitation:
        'HCA routing is not available in the calibrated live project.',
      coverageRef: 'src/accounts/hca.test.ts',
    },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'validators/ens-owner-expired',
    primaryCategory: 'validators',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'hca-ens',
    caseId: 'same-chain-noop',
    axes: {
      account: ['hca', 'state:new'],
      owner: ['ens:expired', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain', 'calls:single'],
      infrastructure: ['network:offline'],
    },
    tags: ['live-gap', 'golden-vector'],
    support: {
      level: 'offline-only',
      limitation:
        'Release behavior encodes expired ENS ownership without a local clock check.',
      coverageRef: 'src/modules/validators/core.test.ts',
    },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'validators/passkey-single',
    primaryCategory: 'validators',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'safe-passkey',
    caseId: 'same-chain-noop',
    axes: {
      account: ['safe', 'state:new'],
      owner: ['passkey:single', 'validator:default', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain', 'calls:single'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: ['live-gap'],
    support: {
      level: 'dry-run-only',
      limitation: 'WebAuthn execute fixtures are not provisioned.',
    },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'validators/passkey-multiple',
    primaryCategory: 'validators',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'safe-passkey',
    caseId: 'same-chain-noop',
    axes: {
      account: ['safe', 'state:new'],
      owner: ['passkey:multiple', 'threshold:max', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain', 'calls:single'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: ['live-gap', 'negative'],
    support: {
      level: 'dry-run-only',
      limitation: 'WebAuthn execute fixtures are not provisioned.',
    },
    comparison: 'shared-inputs',
    expected: {
      kind: 'failure',
      stage: 'submit',
      errorClass: 'SimulationFailedError',
      code: 'SIMULATION_FAILED',
      messageInvariant: 'CallFailed',
    },
  }),
  intentScenario({
    id: 'validators/mfa-ecdsa-passkey-threshold-aggregation',
    primaryCategory: 'validators',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'safe-mfa',
    caseId: 'same-chain-noop',
    axes: {
      account: ['safe', 'state:new'],
      owner: ['mfa:ecdsa-passkey', 'threshold:max', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain', 'calls:single'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: ['high-risk:mfa-threshold-aggregation', 'live-gap', 'negative'],
    support: {
      level: 'dry-run-only',
      limitation: 'MFA execute credentials are not provisioned.',
    },
    expected: {
      kind: 'failure',
      stage: 'submit',
      errorClass: 'SimulationFailedError',
      code: 'SIMULATION_FAILED',
      messageInvariant: 'CallFailed',
    },
  }),
  intentScenario({
    id: 'validators/stable-numeric-id',
    primaryCategory: 'validators',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'safe-mfa',
    caseId: 'same-chain-noop',
    axes: {
      account: ['safe', 'state:new'],
      owner: ['mfa:ecdsa-passkey', 'id:numeric', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain'],
      infrastructure: ['network:offline'],
    },
    tags: ['golden-vector'],
    support: {
      level: 'offline-only',
      limitation: 'Validator ID vector is local.',
      coverageRef: 'src/execution/independent-signing.test.ts',
    },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'validators/stable-hex-id',
    primaryCategory: 'validators',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'safe-mfa',
    caseId: 'same-chain-noop',
    axes: {
      account: ['safe', 'state:new'],
      owner: ['mfa:ecdsa-passkey', 'id:hex', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain'],
      infrastructure: ['network:offline'],
    },
    tags: ['golden-vector'],
    support: {
      level: 'offline-only',
      limitation: 'Validator ID vector is local.',
      coverageRef: 'src/execution/independent-signing.test.ts',
    },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'validators/threshold-minimum-boundary',
    primaryCategory: 'validators',
    workflow: 'intent',
    mode: 'execute',
    fixtureId: 'safe-threshold',
    caseId: 'same-chain-noop',
    axes: {
      account: ['safe', 'state:new'],
      owner: ['ecdsa:multi-threshold-one', 'threshold:min', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain', 'sponsorship:sponsored'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: ['stateful'],
    support: { level: 'live' },
    expected: { kind: 'success' },
    comparison: 'isolated-state',
    terminalAssertions: ['intent-completed'],
    timeoutMs: 180_000,
  }),
  intentScenario({
    id: 'validators/threshold-maximum-boundary',
    primaryCategory: 'validators',
    workflow: 'intent',
    mode: 'execute',
    fixtureId: 'safe-threshold',
    caseId: 'same-chain-noop',
    axes: {
      account: ['safe', 'state:new'],
      owner: ['ecdsa:multi-threshold-many', 'threshold:max', 'signing:full'],
      session: ['none'],
      operation: ['intent:same-chain', 'sponsorship:sponsored'],
      infrastructure: ['auth:current', 'rpc:default'],
    },
    tags: ['stateful'],
    support: { level: 'live' },
    expected: { kind: 'success' },
    comparison: 'isolated-state',
    terminalAssertions: ['intent-completed'],
    timeoutMs: 180_000,
  }),
  intentScenario({
    id: 'validators/invalid-threshold',
    primaryCategory: 'validators',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'safe-threshold',
    caseId: 'same-chain-noop',
    axes: {
      account: ['safe', 'state:new'],
      owner: ['ecdsa:multi-threshold-many', 'threshold:invalid'],
      session: ['none'],
      operation: ['intent:same-chain'],
      infrastructure: ['network:offline'],
    },
    tags: ['golden-vector'],
    support: {
      level: 'offline-only',
      limitation:
        'Release encodes the invalid threshold without local validation.',
      coverageRef: 'src/modules/validators/core.test.ts',
    },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'validators/custom-module-capability-resolution',
    primaryCategory: 'validators',
    workflow: 'intent',
    mode: 'dryRun',
    fixtureId: 'custom-validator',
    caseId: 'cross-chain-noop',
    axes: {
      account: ['nexus', 'nexus:1.2.0', 'state:new'],
      owner: ['ecdsa:single', 'validator:custom-module', 'signing:full'],
      session: ['none'],
      operation: ['intent:cross-chain'],
      infrastructure: ['auth:current', 'rpc:custom-per-chain'],
    },
    tags: ['high-risk:custom-module-capability-resolution', 'live-gap'],
    support: {
      level: 'dry-run-only',
      limitation: 'Custom module address is not installed in the execute lane.',
    },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'validators/owner-order-permutation',
    primaryCategory: 'validators',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'safe-threshold',
    caseId: 'same-chain-noop',
    axes: {
      account: ['safe', 'state:new'],
      owner: [
        'ecdsa:multi-threshold-many',
        'owner-order:permuted',
        'signing:independent',
      ],
      session: ['none'],
      operation: ['intent:same-chain'],
      infrastructure: ['network:offline'],
    },
    tags: ['golden-vector'],
    support: {
      level: 'offline-only',
      limitation: 'Owner order is compared as a local vector.',
      coverageRef: 'src/execution/independent-signing.test.ts',
    },
    expected: { kind: 'success' },
  }),
  intentScenario({
    id: 'validators/duplicate-independent-contribution',
    primaryCategory: 'validators',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'safe-threshold',
    caseId: 'same-chain-noop',
    axes: {
      account: ['safe', 'state:deployed'],
      owner: [
        'ecdsa:multi-threshold-many',
        'owner:duplicate',
        'signing:independent',
      ],
      session: ['none'],
      operation: ['intent:same-chain'],
      infrastructure: ['network:offline', 'failure:sign'],
    },
    tags: ['negative', 'golden-vector'],
    support: {
      level: 'offline-only',
      limitation: 'Duplicate collection is deterministic locally.',
      coverageRef: 'src/execution/independent-signing.test.ts',
    },
    expected: {
      kind: 'failure',
      stage: 'sign',
      errorClass: 'InsufficientOwnerSignaturesError',
      messageInvariant:
        'Not enough owner signatures to meet the account threshold',
    },
  }),
  intentScenario({
    id: 'validators/missing-signer',
    primaryCategory: 'validators',
    workflow: 'intent',
    mode: 'sign',
    fixtureId: 'safe-ecdsa',
    caseId: 'same-chain-noop',
    axes: {
      account: ['safe', 'state:new'],
      owner: ['ecdsa:single', 'signer:missing'],
      session: ['none'],
      operation: ['intent:same-chain'],
      infrastructure: ['network:offline', 'failure:prepare'],
    },
    tags: ['negative'],
    support: {
      level: 'offline-only',
      limitation: 'Missing signer fails locally.',
      coverageRef:
        'test/characterization/adapters/legacy-gap-contracts.test.ts',
    },
    expected: {
      kind: 'failure',
      stage: 'prepare',
      errorClass: 'WalletClientNoConnectedAccountError',
      messageInvariant: 'WalletClient is missing a default account',
    },
  }),
] as const
