import {
  AccountConfigurationNotSupportedError,
  AccountError,
  DefaultValidatorAlreadyInitializedError,
  Eip712DomainNotAvailableError,
  Eip7702AccountMustHaveEoaError,
  Eip7702NotSupportedForAccountError,
  EoaAccountMustHaveAccountError,
  EoaSigningMethodNotConfiguredError,
  EoaSigningNotSupportedError,
  FactoryArgsNotAvailableError,
  isAccountError,
  ModuleInstallationNotSupportedError,
  OwnersFieldRequiredError,
  SigningNotSupportedForAccountError,
  WalletClientNoConnectedAccountError,
} from '../accounts'
import {
  Eip7702InitSignatureRequiredError,
  ExecutionError,
  IntentFailedError,
  InvalidSourceCallsError,
  isExecutionError,
  OrderPathRequiredForIntentsError,
  QuoteNotInPreparedTransactionError,
} from '../execution'
import type { ErrorDetail } from '../orchestrator'
import {
  ConflictError,
  ExternalServiceTimeoutError,
  ForbiddenError,
  InsufficientLiquidityError,
  InternalServerError,
  isAuthError,
  isOrchestratorError,
  isRateLimited,
  isRetryable,
  isSimulationFailed,
  isValidationError,
  KeyScopeDeniedError,
  NotFoundError,
  OrchestratorError,
  RateLimitedError,
  RelayerMarketUnavailableError,
  SettlementExecutionError,
  SettlementQuoteError,
  SimulationFailedError,
  UnauthorizedError,
  UnprocessableContentError,
  UnsupportedChainError,
  UnsupportedTokenError,
  ValidationError,
} from '../orchestrator'

export type { ErrorDetail }

export {
  // Account
  isAccountError,
  AccountError,
  AccountConfigurationNotSupportedError,
  DefaultValidatorAlreadyInitializedError,
  Eip712DomainNotAvailableError,
  Eip7702AccountMustHaveEoaError,
  Eip7702NotSupportedForAccountError,
  EoaAccountMustHaveAccountError,
  EoaSigningMethodNotConfiguredError,
  EoaSigningNotSupportedError,
  FactoryArgsNotAvailableError,
  ModuleInstallationNotSupportedError,
  OwnersFieldRequiredError,
  SigningNotSupportedForAccountError,
  WalletClientNoConnectedAccountError,
  // Execution
  isExecutionError,
  ExecutionError,
  Eip7702InitSignatureRequiredError,
  IntentFailedError,
  InvalidSourceCallsError,
  OrderPathRequiredForIntentsError,
  QuoteNotInPreparedTransactionError,
  // Orchestrator
  isOrchestratorError,
  isRetryable,
  isAuthError,
  isValidationError,
  isRateLimited,
  isSimulationFailed,
  ConflictError,
  ExternalServiceTimeoutError,
  ForbiddenError,
  InsufficientLiquidityError,
  InternalServerError,
  KeyScopeDeniedError,
  NotFoundError,
  OrchestratorError,
  RateLimitedError,
  RelayerMarketUnavailableError,
  SimulationFailedError,
  SettlementExecutionError,
  SettlementQuoteError,
  UnauthorizedError,
  UnprocessableContentError,
  ValidationError,
  // Registry (SDK-local validation)
  UnsupportedChainError,
  UnsupportedTokenError,
}
