import type { AuthProvider } from '../auth/provider'
import { Orchestrator } from './client'
import { PROD_ORCHESTRATOR_URL, RHINESTONE_SPOKE_POOL_ADDRESS } from './consts'
import {
  type DestinationChain,
  isDestinationChain,
  solanaMainnet,
  tronMainnet,
} from './destinations'
import {
  ConflictError,
  ExternalServiceTimeoutError,
  ForbiddenError,
  InsufficientLiquidityError,
  InternalServerError,
  isAuthError,
  isOrchestratorError,
  isRateLimited,
  isRetryable,
  isValidationError,
  NotFoundError,
  OrchestratorError,
  RateLimitedError,
  RelayerMarketUnavailableError,
  SettlementExecutionError,
  SettlementQuoteError,
  UnauthorizedError,
  UnprocessableContentError,
  UnsupportedChainError,
  UnsupportedTokenError,
  ValidationError,
} from './error'
import {
  getTokenSymbol,
  getWethAddress,
  isTokenAddressSupported,
} from './registry'
import type {
  ApprovalRequired,
  AuxiliaryFunds,
  BridgeFill,
  Cost,
  CostTokenEntry,
  EstimatedFillTime,
  Execution,
  FeeBreakdown,
  Fees,
  FillTransactionHash,
  IntentInput,
  IntentOpStatus,
  IntentOptions,
  IntentSubmitRequest,
  IntentSubmitResponse,
  Portfolio,
  Price,
  Quote,
  QuoteResponse,
  SettlementLayer,
  SettlementLayerFilter,
  SignatureMode,
  SignData,
  SignedAuthorization,
  SplitIntentsInput,
  SplitIntentsResult,
  SponsorSettings,
  SupportedChain,
  TokenConfig,
  TokenRequirements,
  TypedDataDefinition,
  UsdAmount,
  WrapRequired,
} from './types'
import {
  INTENT_STATUS_CLAIMED,
  INTENT_STATUS_COMPLETED,
  INTENT_STATUS_EXPIRED,
  INTENT_STATUS_FAILED,
  INTENT_STATUS_FILLED,
  INTENT_STATUS_PENDING,
  INTENT_STATUS_PRECONFIRMED,
} from './types'

function getOrchestrator(
  authProvider: AuthProvider,
  orchestratorUrl?: string,
  headers?: Record<string, string>,
): Orchestrator {
  return new Orchestrator(
    orchestratorUrl ?? PROD_ORCHESTRATOR_URL,
    authProvider,
    headers,
  )
}

export type {
  ApprovalRequired,
  AuxiliaryFunds,
  BridgeFill,
  Cost,
  CostTokenEntry,
  DestinationChain,
  EstimatedFillTime,
  Execution,
  FeeBreakdown,
  Fees,
  FillTransactionHash,
  IntentInput,
  IntentOpStatus,
  IntentOptions,
  IntentSubmitRequest,
  IntentSubmitResponse,
  Portfolio,
  Price,
  Quote,
  QuoteResponse,
  SettlementLayer,
  SettlementLayerFilter,
  SignatureMode,
  SignData,
  SignedAuthorization,
  SplitIntentsInput,
  SplitIntentsResult,
  SponsorSettings,
  SupportedChain,
  TokenConfig,
  TokenRequirements,
  TypedDataDefinition,
  UsdAmount,
  WrapRequired,
}
export {
  isDestinationChain,
  solanaMainnet,
  tronMainnet,
  INTENT_STATUS_PENDING,
  INTENT_STATUS_EXPIRED,
  INTENT_STATUS_COMPLETED,
  INTENT_STATUS_FILLED,
  INTENT_STATUS_FAILED,
  INTENT_STATUS_PRECONFIRMED,
  INTENT_STATUS_CLAIMED,
  RHINESTONE_SPOKE_POOL_ADDRESS,
  Orchestrator,
  ConflictError,
  ExternalServiceTimeoutError,
  ForbiddenError,
  InsufficientLiquidityError,
  InternalServerError,
  NotFoundError,
  OrchestratorError,
  RateLimitedError,
  RelayerMarketUnavailableError,
  SettlementExecutionError,
  SettlementQuoteError,
  UnauthorizedError,
  UnprocessableContentError,
  UnsupportedChainError,
  UnsupportedTokenError,
  ValidationError,
  getOrchestrator,
  getWethAddress,
  getTokenSymbol,
  isOrchestratorError,
  isRetryable,
  isAuthError,
  isValidationError,
  isRateLimited,
  isTokenAddressSupported,
}
