import type { AuthProvider } from '../auth/provider'
import { Orchestrator } from './client'
import { PROD_ORCHESTRATOR_URL, RHINESTONE_SPOKE_POOL_ADDRESS } from './consts'
import {
  AuthenticationRequiredError,
  BadRequestError,
  BodyParserError,
  ConflictError,
  ForbiddenError,
  InsufficientBalanceError,
  InsufficientLiquidityError,
  IntentNotFoundError,
  InternalServerError,
  InvalidApiKeyError,
  InvalidIntentSignatureError,
  isAuthError,
  isOrchestratorError,
  isRateLimited,
  isRetryable,
  isValidationError,
  NoPathFoundError,
  OnlyOneTargetTokenAmountCanBeUnsetError,
  OrchestratorError,
  RateLimitedError,
  ResourceNotFoundError,
  SchemaValidationError,
  ServiceUnavailableError,
  SimulationFailedError,
  TokenNotSupportedError,
  UnauthorizedError,
  UnprocessableEntityError,
  UnsupportedChainError,
  UnsupportedChainIdError,
  UnsupportedTokenError,
} from './error'
import {
  getAllSupportedChainsAndTokens,
  getSupportedTokens,
  getTokenAddress,
  getTokenDecimals,
  getTokenSymbol,
  getWethAddress,
  isTokenAddressSupported,
} from './registry'
import type {
  AppFee,
  AppFeeBalances,
  AppFeeRate,
  ApprovalRequired,
  AuxiliaryFunds,
  Execution,
  IntentInput,
  IntentOp,
  IntentOpStatus,
  IntentResult,
  IntentRoute,
  Portfolio,
  SettlementLayer,
  SignedIntentOp,
  SplitIntentsInput,
  SplitIntentsResult,
  SupportedChain,
  TokenConfig,
  TokenRequirements,
  WrapRequired,
} from './types'
import {
  INTENT_STATUS_CLAIMED,
  INTENT_STATUS_COMPLETED,
  INTENT_STATUS_EXPIRED,
  INTENT_STATUS_FAILED,
  INTENT_STATUS_FILLED,
  INTENT_STATUS_PENDING,
  INTENT_STATUS_PRECONFIRMED,
} from './types'

function getOrchestrator(
  authProvider: AuthProvider,
  orchestratorUrl?: string,
  headers?: Record<string, string>,
): Orchestrator {
  return new Orchestrator(
    orchestratorUrl ?? PROD_ORCHESTRATOR_URL,
    authProvider,
    headers,
  )
}

export type {
  AppFee,
  AppFeeBalances,
  AppFeeRate,
  ApprovalRequired,
  AuxiliaryFunds,
  Execution,
  IntentInput,
  IntentOp,
  IntentOpStatus,
  IntentResult,
  IntentRoute,
  Portfolio,
  SettlementLayer,
  SignedIntentOp,
  SplitIntentsInput,
  SplitIntentsResult,
  SupportedChain,
  TokenConfig,
  TokenRequirements,
  WrapRequired,
}
export {
  AuthenticationRequiredError,
  BadRequestError,
  BodyParserError,
  ConflictError,
  ForbiddenError,
  getAllSupportedChainsAndTokens,
  getOrchestrator,
  getSupportedTokens,
  getTokenAddress,
  getTokenDecimals,
  getTokenSymbol,
  getWethAddress,
  INTENT_STATUS_CLAIMED,
  INTENT_STATUS_COMPLETED,
  INTENT_STATUS_EXPIRED,
  INTENT_STATUS_FAILED,
  INTENT_STATUS_FILLED,
  INTENT_STATUS_PENDING,
  INTENT_STATUS_PRECONFIRMED,
  InsufficientBalanceError,
  InsufficientLiquidityError,
  IntentNotFoundError,
  InternalServerError,
  InvalidApiKeyError,
  InvalidIntentSignatureError,
  isAuthError,
  isOrchestratorError,
  isRateLimited,
  isRetryable,
  isTokenAddressSupported,
  isValidationError,
  NoPathFoundError,
  OnlyOneTargetTokenAmountCanBeUnsetError,
  Orchestrator,
  OrchestratorError,
  RateLimitedError,
  ResourceNotFoundError,
  RHINESTONE_SPOKE_POOL_ADDRESS,
  SchemaValidationError,
  ServiceUnavailableError,
  SimulationFailedError,
  TokenNotSupportedError,
  UnauthorizedError,
  UnprocessableEntityError,
  UnsupportedChainError,
  UnsupportedChainIdError,
  UnsupportedTokenError,
}
