import {
  type IdentityMapping,
  type NormalizationKind,
  type NormalizationResult,
  normalizeObservation,
  type NormalizationRule as PathNormalizationRule,
} from './normalize'
import type { CharacterizationObservation } from './observe'
import type { NormalizationRule as CatalogNormalizationRule } from './types'

export const NORMALIZER_VERSION = 2

type RuleDefinition = {
  readonly kind: NormalizationKind
  readonly reason: string
  readonly matches: (key: string) => boolean
}

const NAMED_NORMALIZATION_RULES = {
  'request-id': {
    kind: 'generated-id',
    reason: 'request and trace correlation IDs are generated for each run',
    matches: (key) => key === 'requestid' || key === 'traceid',
  },
  'quote-id': {
    kind: 'generated-id',
    reason: 'quote and intent IDs are generated by the quoting service',
    matches: (key) => key === 'quoteid' || key === 'intentid',
  },
  timestamps: {
    kind: 'timestamp',
    reason: 'service observation timestamps depend on wall-clock time',
    matches: (key) =>
      ['timestamp', 'createdat', 'updatedat', 'observedat'].includes(key),
  },
  'gas-estimates': {
    kind: 'gas-estimate',
    reason: 'gas estimates depend on the current network state',
    matches: (key) => key.includes('gas') && key.includes('estimate'),
  },
  'transaction-hash': {
    kind: 'transaction-hash',
    reason: 'transaction hashes identify individual live submissions',
    matches: (key) => ['transactionhash', 'txhash'].includes(key),
  },
  'receipt-block': {
    kind: 'block-number',
    reason: 'receipt block numbers depend on the testnet head',
    matches: (key) => key === 'blocknumber',
  },
} as const satisfies Record<CatalogNormalizationRule, RuleDefinition>

export interface ScenarioNormalizationResult extends NormalizationResult {
  readonly rules: readonly PathNormalizationRule[]
}

function normalizeFieldName(name: string): string {
  return name.replace(/[^a-z0-9]/giu, '').toLowerCase()
}

function encodePointerSegment(segment: string): string {
  return segment.replace(/~/gu, '~0').replace(/\//gu, '~1')
}

function childPath(path: string, segment: string | number): string {
  return `${path}/${encodePointerSegment(String(segment))}`
}

function comparableObservation(
  observation: CharacterizationObservation,
): Record<string, unknown> {
  const {
    schemaVersion: _schemaVersion,
    scenarioId: _scenarioId,
    subject: _subject,
    runId: _runId,
    comparisonGroup: _comparisonGroup,
    ...comparable
  } = observation
  return comparable
}

export function resolveNormalizationRules(
  observation: CharacterizationObservation,
  selected: readonly CatalogNormalizationRule[],
): PathNormalizationRule[] {
  const selectedDefinitions = selected.map(
    (name) => [name, NAMED_NORMALIZATION_RULES[name]] as const,
  )
  const rules: PathNormalizationRule[] = []
  const active = new WeakSet<object>()

  function visit(current: unknown, path: string): void {
    if (typeof current !== 'object' || current === null) return
    if (active.has(current)) {
      throw new TypeError(
        `Cannot resolve normalization rules for cyclic value at ${path || '/'}`,
      )
    }
    active.add(current)

    try {
      if (current instanceof Date) return
      if (current instanceof Map) {
        let index = 0
        for (const [key, value] of current.entries()) {
          visit(key, childPath(childPath(path, index), 'key'))
          visit(value, childPath(childPath(path, index), 'value'))
          index += 1
        }
        return
      }
      if (Array.isArray(current)) {
        current.forEach((value, index) => visit(value, childPath(path, index)))
        return
      }

      for (const [key, value] of Object.entries(current)) {
        const normalizedKey = normalizeFieldName(key)
        const child = childPath(path, key)
        for (const [, definition] of selectedDefinitions) {
          if (definition.matches(normalizedKey)) {
            rules.push({
              path: child,
              kind: definition.kind,
              reason: definition.reason,
            })
          }
        }
        visit(value, child)
      }
    } finally {
      active.delete(current)
    }
  }

  visit(comparableObservation(observation), '')
  return rules
}

export function normalizeScenarioObservation(
  observation: CharacterizationObservation,
  selected: readonly CatalogNormalizationRule[],
  identityMappings: readonly IdentityMapping[] = [],
): ScenarioNormalizationResult {
  const comparable = comparableObservation(observation)
  const rules = resolveNormalizationRules(observation, selected)
  const normalized = normalizeObservation(comparable, {
    rules,
    identityMappings,
  })
  return { ...normalized, rules }
}
