/**
 * Generates `src/clients/orchestrator/wire.gen.ts` from the orchestrator's published
 * OpenAPI spec (blanc version). The generated wire types are the single source
 * of truth for the orchestrator's request/response shapes; the orchestrator
 * client adapts them to the SDK's internal types (BigInt amounts, numeric chain
 * ids). When the wire shape drifts, regenerating this file turns the change into
 * a typecheck error at the adapter boundary.
 *
 * Spec source resolves as: CLI arg → `ORCH_OPENAPI_SPEC` env → published URL.
 * The published spec lives in the public `rhinestonewtf/openapi` repo, so the
 * default needs no auth. Pass a local path to generate against a checkout.
 */
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'

const DEFAULT_SPEC =
  'https://raw.githubusercontent.com/rhinestonewtf/openapi/main/orchestrator/blanc.json'

const OUT_PATH = fileURLToPath(
  new URL('../src/clients/orchestrator/wire.gen.ts', import.meta.url),
)

function resolveSpec(value: string): URL {
  if (/^https?:\/\//.test(value)) return new URL(value)
  return pathToFileURL(resolve(process.cwd(), value))
}

async function main() {
  const spec = process.argv[2] ?? process.env.ORCH_OPENAPI_SPEC ?? DEFAULT_SPEC
  const input = resolveSpec(spec)
  console.info(`Generating wire types from: ${input.href}`)
  const ast = await openapiTS(input)
  const banner =
    '/**\n * Generated by `bun run generate:wire` from the orchestrator OpenAPI spec.\n * Do not edit by hand — regenerate instead.\n */\n'
  writeFileSync(OUT_PATH, banner + astToString(ast))
  console.info(`Wrote ${OUT_PATH}`)
}

main()
