import { RhinestoneSDK } from './api/sdk'
import {
  hyperCorePerp,
  hyperCoreSpot,
  solanaAddress,
  solanaDevnet,
  solanaMainnet,
  stellarMainnet,
  tronMainnet,
} from './chains/non-evm'
import {
  MULTI_FACTOR_VALIDATOR_ADDRESS,
  MULTI_FACTOR_VALIDATOR_V2_ADDRESS,
} from './modules/validators/multi-factor'
import { OWNABLE_VALIDATOR_ADDRESS } from './modules/validators/ownable'
import { SMART_SESSION_EMISSARY_ADDRESS } from './modules/validators/smart-sessions/module'
import { WEBAUTHN_VALIDATOR_ADDRESS } from './modules/validators/webauthn'

export {
  RhinestoneSDK,
  // Non-viem destination chain descriptors (Solana, Tron, Stellar, HyperCore)
  hyperCorePerp,
  hyperCoreSpot,
  solanaAddress,
  solanaDevnet,
  solanaMainnet,
  stellarMainnet,
  tronMainnet,
  // Validator addresses
  OWNABLE_VALIDATOR_ADDRESS,
  WEBAUTHN_VALIDATOR_ADDRESS,
  MULTI_FACTOR_VALIDATOR_ADDRESS,
  MULTI_FACTOR_VALIDATOR_V2_ADDRESS,
  SMART_SESSION_EMISSARY_ADDRESS,
}

export type {
  ManagedEvmAccount,
  ManagedTransactionAccount,
  RhinestoneAccount,
  RhinestoneAccountBase,
  SignedIntentData,
} from './api/account'
export type {
  DestinationChain,
  HyperCoreChain,
  NonEvmAddress,
  NonEvmChain,
  SolanaAccountMeta,
  SolanaAddress,
  SolanaChain,
  SolanaInstruction,
  SolanaInstructionInput,
  SolanaProgramInstruction,
  StellarChain,
  TronChain,
} from './chains/non-evm'
export type {
  AppFeeBalances,
  AppFeeRate,
  AuxiliaryFunds,
  BridgeFill,
  Caip2ChainId,
  FailureReason,
  HyperCoreAction,
  HyperCoreBatchModifyAction,
  HyperCoreCancelAction,
  HyperCoreCancelByCloidAction,
  HyperCoreModifyAction,
  HyperCoreOrder,
  HyperCoreOrderAction,
  HyperCoreOrderType,
  HyperCoreTimeInForce,
  HyperCoreUpdateIsolatedMarginAction,
  HyperCoreUpdateLeverageAction,
  IntentAccountSummary,
  IntentAccountView,
  IntentDetails,
  IntentExecutionOperation,
  IntentHyperCoreResult,
  IntentInput,
  IntentLeg,
  IntentOnchainOperation,
  IntentOperationAllocation,
  IntentOperationGroup,
  IntentOperationItem,
  IntentOpStatus,
  IntentRefund,
  IntentRequirement,
  OperationStatus,
  PlanExecution,
  PlanLeg,
  Portfolio,
  ProtocolFeeRate,
  Quote,
  QuotePlan,
  SerializedIntentInput,
  SettlementLayer,
  SettlementLayerFilter,
  SigningAuthority,
  SigningPayload,
  SigningProof,
  SigningRequest,
  SigningRequestAccount,
  SigningRequestPurpose,
  SigningScope,
  SigningValidity,
  SplitIntentsInput,
  SplitIntentsResult,
  SwapQuoter,
  SwapQuoterFilter,
  TransactionReference,
  WebAuthnAssertion,
} from './clients/orchestrator/public'
export type {
  AccountProviderConfig,
  AccountTransaction,
  AccountType,
  BundlerConfig,
  Call,
  CallInput,
  ChainSessionConfig,
  ClosePerpRequest,
  CrossChainPermissionInput,
  CrossChainPermit,
  CrossChainSettlementLayer,
  CrossChainSolanaOriginTransaction,
  EvmAccountConfig,
  EvmAccountEntry,
  EvmReceiverAccountConfig,
  FromLeg,
  GuardiansSignerSet,
  HyperCoreOptions,
  HyperliquidConfig,
  MultiFactorValidatorConfig,
  NonEvmTokenRequest,
  NonEvmTokenRequests,
  OpenPerpRequest,
  OwnableValidatorConfig,
  OwnerSet,
  ParamConstraint,
  PaymasterConfig,
  Permission,
  PermissionFunctionConfig,
  Permit2ClaimPolicy,
  Policy,
  ProviderConfig,
  QuorumOwner,
  QuorumValidatorConfig,
  Recovery,
  RhinestoneAccountConfig,
  SameChainSolanaInstructionsTransaction,
  SameChainSolanaTransaction,
  Session,
  SessionDefinition,
  SessionSigning,
  SessionSigningContent,
  SignerSet,
  SolanaAccountConfig,
  SolanaManagedAccountConfig,
  SolanaOwner,
  SolanaReceiverAccountConfig,
  SourceCallInput,
  SourceCallProvidedFunds,
  SwapScope,
  TokenRequest,
  TokenSymbol,
  ToLeg,
  Transaction,
  UniversalActionPolicyParamCondition,
  WebauthnValidatorConfig,
} from './config/account'
export type {
  OwnerPasskeySignature,
  OwnerSignature,
  OwnerSignatureData,
  SignAsOwnerOptions,
} from './signing/types'
export type {
  PreparedQuotes,
  PreparedTransactionData,
  QuoteSelection,
  SignedTransactionData,
  SolanaCrossChainExecutionMetadata,
  SolanaExecutionMetadata,
  SolanaInstructionsExecutionMetadata,
  TransactionResult,
} from './transactions/intents/types'
export type {
  PreparedUserOperationData,
  SignedUserOperationData,
  UserOperationResult,
} from './transactions/user-operations/types'
